// Catalog of every event type. Keep in sync with reducer/selectors.

export const EVENT_TYPES = {
  // Creator-level (portal status family — global per creator)
  CREATOR_ADDED: 'CREATOR_ADDED',
  PORTAL_INVITE_SENT: 'PORTAL_INVITE_SENT',
  PORTAL_INVITE_VIEWED: 'PORTAL_INVITE_VIEWED',
  PORTAL_INVITE_DISMISSED: 'PORTAL_INVITE_DISMISSED',
  ONBOARDING_STARTED: 'ONBOARDING_STARTED',
  ONBOARDING_PARTIAL: 'ONBOARDING_PARTIAL',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  PREFERENCES_EMAIL_SENT: 'PREFERENCES_EMAIL_SENT',
  NUDGE_SENT: 'NUDGE_SENT',
  NOTE_ADDED: 'NOTE_ADDED',

  // Brand-pool family (per creator × brand) — three-level qualification
  BRAND_POOL_ADDED: 'BRAND_POOL_ADDED',           // → Potential
  BRAND_POOL_CONFIRMED: 'BRAND_POOL_CONFIRMED',   // → Confirmed (preferences reviewed)
  BRAND_POOL_QUALIFIED: 'BRAND_POOL_QUALIFIED',   // → Qualified (full vetting + AI card complete)
  BRAND_POOL_ARCHIVED: 'BRAND_POOL_ARCHIVED',
  BRAND_POOL_UNARCHIVED: 'BRAND_POOL_UNARCHIVED',

  // AI brand-facing card (per creator × campaign)
  AI_CARD_GENERATED: 'AI_CARD_GENERATED',
  AI_CARD_REVIEWED: 'AI_CARD_REVIEWED',
  AI_CARD_REWORKED: 'AI_CARD_REWORKED',

  // Scoring + post-campaign
  CAMPAIGN_RATED: 'CAMPAIGN_RATED',                // payload: { rating: 1-10, campaignId }
  POST_COMPLIANCE_LOGGED: 'POST_COMPLIANCE_LOGGED', // payload: { posted: bool, platform, on_time }

  // Brand-context family (per brand)
  BRAND_NOTE_ADDED: 'BRAND_NOTE_ADDED',
  BRAND_CONTEXT_UPDATED: 'BRAND_CONTEXT_UPDATED',

  // Campaign-scoped
  ASSIGNED_TO_CAMPAIGN: 'ASSIGNED_TO_CAMPAIGN',
  CAMPAIGN_DETAILS_VIEWED: 'CAMPAIGN_DETAILS_VIEWED',
  CAMPAIGN_BRIEF_SCROLLED: 'CAMPAIGN_BRIEF_SCROLLED',
  CAMPAIGN_ACCEPTED: 'CAMPAIGN_ACCEPTED',
  CAMPAIGN_DECLINED: 'CAMPAIGN_DECLINED',
  PRODUCT_SELECTED: 'PRODUCT_SELECTED',
  PRODUCT_DESELECTED: 'PRODUCT_DESELECTED',
  ORDER_PLACED: 'ORDER_PLACED',
  PRODUCT_SHIPPED: 'PRODUCT_SHIPPED',
  DELIVERY_CONFIRMED: 'DELIVERY_CONFIRMED',
  DELIVERY_DECLINED: 'DELIVERY_DECLINED',
  CONTENT_SUBMITTED: 'CONTENT_SUBMITTED',
  CONTENT_REVISION_REQUESTED: 'CONTENT_REVISION_REQUESTED',
  CONTENT_APPROVED: 'CONTENT_APPROVED',
  CONTENT_LIVE: 'CONTENT_LIVE',
  BENABLE_RECS_ADDED: 'BENABLE_RECS_ADDED',
  VISIBLE_TO_BRAND_TOGGLED: 'VISIBLE_TO_BRAND_TOGGLED',
  BRAND_INVITED: 'BRAND_INVITED',
  BRAND_ACCEPTED: 'BRAND_ACCEPTED',
  BRAND_REJECTED: 'BRAND_REJECTED',
  BRAND_NO_RESPONSE: 'BRAND_NO_RESPONSE',
};

export const CAMPAIGN_SCOPED_TYPES = new Set([
  EVENT_TYPES.ASSIGNED_TO_CAMPAIGN,
  EVENT_TYPES.CAMPAIGN_DETAILS_VIEWED,
  EVENT_TYPES.CAMPAIGN_BRIEF_SCROLLED,
  EVENT_TYPES.CAMPAIGN_ACCEPTED,
  EVENT_TYPES.CAMPAIGN_DECLINED,
  EVENT_TYPES.PRODUCT_SELECTED,
  EVENT_TYPES.PRODUCT_DESELECTED,
  EVENT_TYPES.ORDER_PLACED,
  EVENT_TYPES.PRODUCT_SHIPPED,
  EVENT_TYPES.DELIVERY_CONFIRMED,
  EVENT_TYPES.DELIVERY_DECLINED,
  EVENT_TYPES.CONTENT_SUBMITTED,
  EVENT_TYPES.CONTENT_REVISION_REQUESTED,
  EVENT_TYPES.CONTENT_APPROVED,
  EVENT_TYPES.CONTENT_LIVE,
  EVENT_TYPES.BENABLE_RECS_ADDED,
  EVENT_TYPES.VISIBLE_TO_BRAND_TOGGLED,
  EVENT_TYPES.BRAND_INVITED,
  EVENT_TYPES.BRAND_ACCEPTED,
  EVENT_TYPES.BRAND_REJECTED,
  EVENT_TYPES.BRAND_NO_RESPONSE,
]);

let nonce = 0;
export function makeEventId() {
  nonce += 1;
  return `evt_${Date.now().toString(36)}_${nonce.toString(36)}_${Math.random().toString(36).slice(2, 7)}`;
}

export function makeEvent({ type, creatorId, campaignId, brandId, timestamp, actor, payload }) {
  return {
    id: makeEventId(),
    type,
    creatorId: creatorId ?? null,
    campaignId: campaignId ?? null,
    brandId: brandId ?? null,
    timestamp: timestamp ?? new Date().toISOString(),
    actor: actor ?? { kind: 'system' },
    payload: payload ?? {},
  };
}
