// Brands as first-class entities. Each brand has context, contacts, and is
// the parent of one or more campaigns. Operational state (onboarding,
// contract, billing) is derived from BRAND_* events.

export const SEED_BRANDS = [
  {
    id: 'brand_aubree_says',
    name: 'Aubree Says',
    handle: '@aubree-says',
    logoColor: 'A',
    provenance: 'Post-event outreach (Spring Creator Fair, Mar 2026)',
    relationshipType: 'Direct',
    contactName: 'Aubree Reilly',
    contactEmail: 'aubree@aubreesays.com',
    paid: false,
    rate: null,
    subscribedSince: '2026-03-12',
    monthlyCampaigns: 1.5,
    avgInviteToAccept: 0.62,
    description: 'Cozy lifestyle brand — apparel + home + gifted-only campaigns.',
    // Initial operational state defaults; overridable via events
    initialOnboarding: 'complete',
    initialContract: 'signed',
    initialBilling: 'active',
  },
  {
    id: 'brand_kinder_living',
    name: 'Kinder Living',
    handle: '@kinder-living',
    logoColor: 'D',
    provenance: 'Demo with Tony · May 3, 2026',
    relationshipType: 'Direct',
    contactName: 'Mei Park',
    contactEmail: 'mei@kinderliving.com',
    paid: false,
    rate: null,
    subscribedSince: '2026-05-03',
    monthlyCampaigns: null,
    avgInviteToAccept: null,
    description: 'New mom-life brand, brief expected this week.',
    initialOnboarding: 'in-progress',
    initialContract: 'signed',
    initialBilling: 'awaiting-first-payment',
  },
  {
    id: 'brand_pikora',
    name: 'Pikora',
    handle: '@pikora',
    logoColor: 'C',
    provenance: 'Inbound — founder cold-DM\'d via Instagram',
    relationshipType: 'Direct',
    contactName: 'Naya Pillai',
    contactEmail: 'naya@pikora.co',
    paid: false,
    rate: null,
    subscribedSince: '2026-02-20',
    monthlyCampaigns: 1,
    avgInviteToAccept: 0.68,
    description: 'Wellness supplements — bone broth + collagen.',
    initialOnboarding: 'complete',
    initialContract: 'signed',
    initialBilling: 'active',
  },
  {
    id: 'brand_home_with_tay',
    name: 'Home with Tay',
    handle: '@homewith.tay',
    logoColor: 'B',
    provenance: 'Direct inbound — founder DM\'d',
    relationshipType: 'Direct',
    contactName: 'Tay Morales',
    contactEmail: 'tay@homewithtay.com',
    paid: false,
    rate: null,
    subscribedSince: '2025-11-20',
    monthlyCampaigns: 0.5,
    avgInviteToAccept: 0.71,
    description: 'Home-and-living brand running occasional gifted drops.',
    initialOnboarding: 'complete',
    initialContract: 'signed',
    initialBilling: 'settled',
  },
];

// Map campaign → brand
export const CAMPAIGN_TO_BRAND = {
  camp_western_cozy: 'brand_aubree_says',
  camp_spring_refresh: 'brand_home_with_tay',
  camp_glow_edit: 'brand_pikora',
  camp_summer_mom: 'brand_kinder_living',
  camp_pikora_bone_broth: 'brand_pikora',
  camp_aubree_holiday: 'brand_aubree_says',
};
