// Empty / partial preferences template
const emptyPrefs = () => ({
  workWith: '',
  avoid: '',
  giftedOpenness: '',
  smallBrands: null,        // 'yes' | 'maybe' | 'no' | null
  smallBrandsNote: '',
  unknownBrands: null,
  unknownBrandsNote: '',
  dreamHousehold: '',
  dreamNiche: '',
  dreamLocal: '',
  about: '',
});

const featurePrefs = {
  cr_dani: {
    about: "Skincare and beauty creator focused on clean ingredients and ethical brands.",
    workWith: "Science-backed, clean ingredients, honest ethics, woman-owned",
    avoid: "Creative freedom being taken away / content altered without credit",
    giftedOpenness: "Open — this is where I'm currently starting",
    smallBrands: 'maybe',
    smallBrandsNote: 'Cautious about ingredients/ethics',
    unknownBrands: 'maybe',
    unknownBrandsNote: 'Same — needs to trust the company',
    dreamHousehold: 'Naturium, Ninja, Costco, Shark',
    dreamNiche: 'Wildfleur, Sprouts',
    dreamLocal: '',
  },
  cr_sage: {
    about: "Mom-life creator — beauty, motherhood, wellness, lifestyle.",
    workWith: "Motherhood, lifestyle, beauty, wellness — clean, non-toxic, practical for mom life",
    avoid: "Not family-friendly, controversial, misleading, low-quality",
    giftedOpenness: "Very open, thankful to be gifted",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'Dyson, Dove, Honest Company',
    dreamNiche: 'Odele Beauty, Branch Basics',
    dreamLocal: 'Gabi Coffee, Mothership Coffee',
  },
  cr_haley: {
    about: "Family content creator covering kids, pets, home, garden.",
    workWith: "Beauty, clothing, pet, kids, outdoor/garden, home, services",
    avoid: "Alcohol (doesn't drink)",
    giftedOpenness: "Open to most!",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'ThredUp, Shark, Love Sac, Quince',
    dreamNiche: 'Crudités, Hulken, Petajane',
    dreamLocal: '',
  },
  cr_ellie: {
    about: "Activewear & beauty creator with a polished, fashion-forward aesthetic.",
    workWith: "Activewear, fashion, skincare, beauty",
    avoid: "Vitamins, food, technology, undergarments, dietary items",
    giftedOpenness: "Very open",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'Vuori, Rhode, H&M, Bloom Nutrition',
    dreamNiche: 'Set Active, Peppermayo, Saie Beauty',
    dreamLocal: 'Sorbo, Timpano, The Salty Donut',
  },
  cr_rylan: {
    about: "Lifestyle creator open to almost any partnership.",
    workWith: "Anyone",
    avoid: "Underwear or sex",
    giftedOpenness: "Very open",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: '',
    dreamNiche: '',
    dreamLocal: '',
  },
  cr_willow: {
    about: "Holistic wellness, clean home, natural living creator.",
    workWith: "Clean ingredients, holistic, natural living, home decor, wellness",
    avoid: "Unsustainable wellness practices",
    giftedOpenness: "Open",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'Purely Elizabeth, Innersense Organic Beauty, Lesser Evil',
    dreamNiche: 'Synergy, Siggs, Bizzy, HU',
    dreamLocal: 'Nitro Bar (RI)',
  },
  cr_carla: {
    about: "Beauty creator focused on clean-ingredient routines.",
    workWith: "Clean ingredients",
    avoid: "",
    giftedOpenness: "Very open",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'Rhode, Youth to the People',
    dreamNiche: 'Culture Pop, Vista Hermosa',
    dreamLocal: 'Sweetgreen, Butterfish',
  },
};

// Defaults for the new fields. Per-creator overrides only what's known.
const defaultLogistics = () => ({
  shippingAddress: null,
  minGiftValue: null,
  usageRightsDuration: '30 days organic',
  usageRightsScope: 'Organic only (reposts, website, emails)',
  postingTimeline: '7-10 days from delivery',
});
const defaultPlatformStats = () => ({
  instagram: { followers: 0, engagement: 0 },
  tiktok: { followers: 0, engagement: 0 },
});
const defaultContentFormatStrengths = () => [];
const defaultAudienceLocations = () => [];

// 7 named feature creators with full data
export const FEATURE_CREATORS = [
  {
    id: 'cr_dani',
    name: 'Dani Brooks',
    firstName: 'Dani',
    handle: '@glowingwithdani',
    benableHandle: 'danibrooks',
    email: 'dani@glowingwithdani.com',
    phone: '+1 555 234 1101',
    locationCity: 'Portland, OR',
    contentNiche: 'Clean beauty + science-led skincare',
    avatarColor: 'A',
    bioAiOptimized: true,
    socials: ['instagram', 'tiktok'],
    followerCount: 4200,
    engagementRate: 18.4,
    platformStats: {
      instagram: { followers: 4200, engagement: 18.4 },
      tiktok: { followers: 1800, engagement: 12.1 },
    },
    contentFormatStrengths: ['face-to-camera', 'reels', 'tutorials'],
    audience: { location: 'United States', genderFemalePct: 91, ageRange: '24-34' },
    audienceTopLocations: [
      { name: 'United States', pct: 78 },
      { name: 'Canada', pct: 9 },
      { name: 'United Kingdom', pct: 5 },
    ],
    categories: ['Beauty', 'Skincare', 'Clean Living'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_dani },
    onboardingStatus: 'complete',
    logistics: {
      ...defaultLogistics(),
      shippingAddress: '4521 NE Alberta St, Portland, OR 97211',
      minGiftValue: 75,
      usageRightsDuration: '30 days organic',
      postingTimeline: '7-14 days (skincare needs time to show results)',
    },
    contentTypePreference: 'social-posts',
  },
  {
    id: 'cr_sage',
    name: 'Sage Apostadiro',
    firstName: 'Sage',
    handle: '@sageylovee',
    benableHandle: 'sageapostadiro',
    email: 'sage@sageylovee.com',
    phone: '+1 555 234 1102',
    locationCity: 'Las Vegas, NV',
    contentNiche: 'Mom life + wellness, clean home',
    avatarColor: 'B',
    bioAiOptimized: true,
    socials: ['instagram'],
    followerCount: 12800,
    engagementRate: 9.2,
    platformStats: {
      instagram: { followers: 12800, engagement: 9.2 },
      tiktok: { followers: 0, engagement: 0 },
    },
    contentFormatStrengths: ['carousels', 'stories', 'face-to-camera'],
    audience: { location: 'United States', genderFemalePct: 88, ageRange: '28-38' },
    audienceTopLocations: [
      { name: 'United States', pct: 82 },
      { name: 'Las Vegas, NV', pct: 14 },
      { name: 'Phoenix, AZ', pct: 6 },
    ],
    categories: ['Motherhood', 'Lifestyle', 'Wellness'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_sage },
    onboardingStatus: 'complete',
    logistics: {
      ...defaultLogistics(),
      shippingAddress: '8821 W Sahara Ave, Las Vegas, NV 89117',
      minGiftValue: 50,
      postingTimeline: '48 hours typical, 1 week for skincare',
    },
    contentTypePreference: 'open-to-both',
  },
  {
    id: 'cr_haley',
    name: 'Haley Brennan',
    firstName: 'Haley',
    handle: '@haleysathome',
    benableHandle: 'haleyathome',
    email: 'haley@haleysathome.com',
    phone: '+1 555 234 1103',
    locationCity: 'Charlotte, NC',
    contentNiche: 'Home, family + garden',
    avatarColor: 'C',
    bioAiOptimized: false,
    socials: ['instagram', 'tiktok'],
    followerCount: 8400,
    engagementRate: 7.1,
    platformStats: {
      instagram: { followers: 8400, engagement: 7.1 },
      tiktok: { followers: 3100, engagement: 9.4 },
    },
    contentFormatStrengths: ['stories', 'carousels'],
    audience: { location: 'United States', genderFemalePct: 84, ageRange: '30-44' },
    audienceTopLocations: [
      { name: 'United States', pct: 91 },
      { name: 'Charlotte, NC', pct: 22 },
    ],
    categories: ['Home', 'Family', 'Outdoor'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_haley },
    onboardingStatus: 'partial',
    logistics: defaultLogistics(),
    contentTypePreference: 'open-to-both',
  },
  {
    id: 'cr_ellie',
    name: 'Ellie Stuart',
    firstName: 'Ellie',
    handle: '@elliestu20',
    benableHandle: 'elliestuart',
    email: 'ellie@elliestuart.com',
    phone: '+1 555 234 1104',
    locationCity: 'Miami, FL',
    contentNiche: 'Activewear + fashion + beauty',
    avatarColor: 'D',
    bioAiOptimized: true,
    socials: ['instagram'],
    followerCount: 6900,
    engagementRate: 11.8,
    platformStats: {
      instagram: { followers: 6900, engagement: 11.8 },
      tiktok: { followers: 0, engagement: 0 },
    },
    contentFormatStrengths: ['reels', 'face-to-camera'],
    audience: { location: 'United States', genderFemalePct: 79, ageRange: '20-30' },
    audienceTopLocations: [
      { name: 'United States', pct: 73 },
      { name: 'Miami, FL', pct: 19 },
      { name: 'United Kingdom', pct: 6 },
    ],
    categories: ['Fashion', 'Activewear', 'Beauty'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_ellie },
    onboardingStatus: 'complete',
    logistics: {
      ...defaultLogistics(),
      shippingAddress: '1245 Brickell Ave, Miami, FL 33131',
      minGiftValue: 100,
    },
    contentTypePreference: 'social-posts',
  },
  {
    id: 'cr_rylan',
    name: 'Rylan Matu',
    firstName: 'Rylan',
    handle: '@rylanmatu',
    benableHandle: 'rylanmatu',
    email: 'rylan@rylanmatu.com',
    phone: '+1 555 234 1105',
    locationCity: 'Los Angeles, CA',
    contentNiche: 'Lifestyle + beauty',
    avatarColor: 'E',
    bioAiOptimized: true,
    socials: ['tiktok'],
    followerCount: 21600,
    engagementRate: 14.5,
    platformStats: {
      instagram: { followers: 0, engagement: 0 },
      tiktok: { followers: 21600, engagement: 14.5 },
    },
    contentFormatStrengths: ['TikTok videos', 'face-to-camera', 'tutorials'],
    audience: { location: 'United States', genderFemalePct: 72, ageRange: '18-28' },
    audienceTopLocations: [
      { name: 'United States', pct: 81 },
      { name: 'Los Angeles, CA', pct: 28 },
    ],
    categories: ['Lifestyle', 'Beauty'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_rylan },
    onboardingStatus: 'complete',
    logistics: {
      ...defaultLogistics(),
      shippingAddress: '8233 Sunset Blvd, Los Angeles, CA 90046',
      minGiftValue: 50,
      postingTimeline: '48 hours typical',
    },
    contentTypePreference: 'open-to-both',
  },
  {
    id: 'cr_willow',
    name: 'Willow Key',
    firstName: 'Willow',
    handle: '@willowkey33',
    benableHandle: 'willowkey',
    email: 'willow@willowkey.com',
    phone: '+1 555 234 1106',
    locationCity: 'Providence, RI',
    contentNiche: 'Holistic wellness + clean home',
    avatarColor: 'F',
    bioAiOptimized: true,
    socials: ['instagram', 'tiktok'],
    followerCount: 9500,
    engagementRate: 13.0,
    platformStats: {
      instagram: { followers: 9500, engagement: 13.0 },
      tiktok: { followers: 4200, engagement: 11.5 },
    },
    contentFormatStrengths: ['reels', 'carousels', 'stories'],
    audience: { location: 'United States', genderFemalePct: 86, ageRange: '26-38' },
    audienceTopLocations: [
      { name: 'United States', pct: 88 },
      { name: 'Boston, MA', pct: 12 },
      { name: 'Providence, RI', pct: 8 },
    ],
    categories: ['Wellness', 'Home', 'Holistic'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_willow },
    onboardingStatus: 'complete',
    logistics: {
      ...defaultLogistics(),
      shippingAddress: '52 Westminster St, Providence, RI 02903',
      minGiftValue: 75,
      usageRightsScope: 'Organic only — no paid amplification without separate license',
    },
    contentTypePreference: 'open-to-both',
  },
  {
    id: 'cr_carla',
    name: 'Carla Guillarte',
    firstName: 'Carla',
    handle: '@carlacharisse',
    benableHandle: 'carlaguillarte',
    email: 'carla@carlacharisse.com',
    phone: '+1 555 234 1107',
    locationCity: 'New York, NY',
    contentNiche: 'Clean beauty routines',
    avatarColor: 'G',
    bioAiOptimized: true,
    socials: ['instagram'],
    followerCount: 5100,
    engagementRate: 16.2,
    platformStats: {
      instagram: { followers: 5100, engagement: 16.2 },
      tiktok: { followers: 0, engagement: 0 },
    },
    contentFormatStrengths: ['reels', 'face-to-camera', 'tutorials'],
    audience: { location: 'United States', genderFemalePct: 89, ageRange: '24-34' },
    audienceTopLocations: [
      { name: 'United States', pct: 76 },
      { name: 'New York, NY', pct: 24 },
    ],
    categories: ['Beauty', 'Skincare'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_carla },
    onboardingStatus: 'complete',
    logistics: {
      ...defaultLogistics(),
      shippingAddress: '420 W 23rd St, New York, NY 10011',
      minGiftValue: 100,
    },
    contentTypePreference: 'social-posts',
  },
];

// Pool of plausible creator data for the 43 generic creators
const GENERIC_POOL = [
  { name: 'Avery Lin', handle: '@averythelin', categories: ['Lifestyle', 'Fashion'], followers: 3400, eng: 9.1, gender: 78, age: '22-32' },
  { name: 'Bri Sanders', handle: '@brisanders', categories: ['Beauty', 'Skincare'], followers: 7200, eng: 11.5, gender: 92, age: '24-34' },
  { name: 'Camila Rios', handle: '@camilariosss', categories: ['Fashion', 'Travel'], followers: 11400, eng: 8.4, gender: 81, age: '25-35' },
  { name: 'Drea Park', handle: '@dreaparkliving', categories: ['Home', 'Lifestyle'], followers: 5600, eng: 12.3, gender: 87, age: '28-40' },
  { name: 'Esme Tucker', handle: '@esmetucks', categories: ['Wellness', 'Fitness'], followers: 9100, eng: 10.7, gender: 74, age: '23-33' },
  { name: 'Faye Romero', handle: '@fayeromero', categories: ['Motherhood', 'Family'], followers: 18500, eng: 6.9, gender: 95, age: '30-44' },
  { name: 'Gianna Webb', handle: '@giannaweb', categories: ['Beauty'], followers: 4200, eng: 14.2, gender: 90, age: '20-30' },
  { name: 'Hadley Kim', handle: '@hadleyk', categories: ['Lifestyle', 'Beauty'], followers: 22300, eng: 7.5, gender: 82, age: '26-36' },
  { name: 'Imani Joseph', handle: '@imanijoseph', categories: ['Fashion', 'Beauty'], followers: 6700, eng: 11.1, gender: 88, age: '24-34' },
  { name: 'Jules Bishop', handle: '@julesatcasa', categories: ['Home', 'Decor'], followers: 14200, eng: 9.8, gender: 79, age: '30-44' },
  { name: 'Kira Pham', handle: '@kirapham', categories: ['Wellness', 'Beauty'], followers: 8900, eng: 12.6, gender: 86, age: '26-38' },
  { name: 'Lila Anders', handle: '@lilaanders', categories: ['Lifestyle', 'Travel'], followers: 5300, eng: 13.8, gender: 76, age: '22-32' },
  { name: 'Mira Owens', handle: '@miraowens', categories: ['Fitness', 'Wellness'], followers: 16800, eng: 8.2, gender: 71, age: '24-34' },
  { name: 'Nia Carter', handle: '@niacarterlife', categories: ['Beauty', 'Skincare'], followers: 4800, eng: 15.4, gender: 93, age: '22-32' },
  { name: 'Opal Reyes', handle: '@opalreyes', categories: ['Fashion'], followers: 10300, eng: 9.5, gender: 84, age: '25-35' },
  { name: 'Piper Wynn', handle: '@piperwynn', categories: ['Motherhood', 'Beauty'], followers: 7600, eng: 10.9, gender: 94, age: '28-40' },
  { name: 'Quinn Holloway', handle: '@quinnholloway', categories: ['Lifestyle', 'Home'], followers: 12100, eng: 8.7, gender: 80, age: '28-42' },
  { name: 'Rae Castillo', handle: '@raecastillo', categories: ['Beauty', 'Fashion'], followers: 4500, eng: 13.1, gender: 89, age: '20-30' },
  { name: 'Sloane Patel', handle: '@sloanepatel', categories: ['Wellness', 'Holistic'], followers: 9700, eng: 11.4, gender: 85, age: '26-38' },
  { name: 'Tess Greaves', handle: '@tessgreaves', categories: ['Lifestyle', 'Family'], followers: 6300, eng: 10.2, gender: 88, age: '30-44' },
  { name: 'Uma Brooks', handle: '@umab', categories: ['Beauty'], followers: 3100, eng: 16.0, gender: 91, age: '20-30' },
  { name: 'Vera Goodall', handle: '@verakindly', categories: ['Wellness', 'Fitness'], followers: 13500, eng: 7.9, gender: 76, age: '24-36' },
  { name: 'Wren Davies', handle: '@wrendavies', categories: ['Fashion', 'Travel'], followers: 8200, eng: 9.3, gender: 81, age: '26-36' },
  { name: 'Xio Mendez', handle: '@xiomendez', categories: ['Beauty', 'Lifestyle'], followers: 5900, eng: 12.0, gender: 87, age: '22-32' },
  { name: 'Yasmin Day', handle: '@yasminday', categories: ['Motherhood', 'Wellness'], followers: 19400, eng: 6.4, gender: 96, age: '32-44' },
  { name: 'Zoe Anand', handle: '@zoeaanand', categories: ['Lifestyle'], followers: 4000, eng: 14.7, gender: 83, age: '22-32' },
  { name: 'Adair Hunt', handle: '@adairhunt', categories: ['Home', 'Lifestyle'], followers: 7400, eng: 10.5, gender: 78, age: '28-42' },
  { name: 'Bex McCoy', handle: '@bexmccoy', categories: ['Beauty', 'Skincare'], followers: 11900, eng: 8.6, gender: 92, age: '24-34' },
  { name: 'Cleo Tanaka', handle: '@cleotanaka', categories: ['Fashion'], followers: 25700, eng: 7.2, gender: 80, age: '22-32' },
  { name: 'Della Rivers', handle: '@dellarivers', categories: ['Beauty', 'Lifestyle'], followers: 6100, eng: 11.7, gender: 89, age: '24-34' },
  { name: 'Elsie Tate', handle: '@elsietate', categories: ['Wellness'], followers: 4700, eng: 13.3, gender: 84, age: '26-38' },
  { name: 'Frankie Locke', handle: '@frankielocke', categories: ['Lifestyle', 'Travel'], followers: 14800, eng: 8.0, gender: 75, age: '24-34' },
  { name: 'Greta Hollis', handle: '@gretahollis', categories: ['Home', 'Family'], followers: 9300, eng: 9.7, gender: 91, age: '30-44' },
  { name: 'Hattie Boyle', handle: '@hattieboyle', categories: ['Beauty'], followers: 3600, eng: 15.9, gender: 88, age: '20-30' },
  { name: 'Indi Stark', handle: '@indistark', categories: ['Fashion', 'Beauty'], followers: 8800, eng: 11.0, gender: 82, age: '22-32' },
  { name: 'Jovi Marsh', handle: '@jovimarsh', categories: ['Wellness', 'Fitness'], followers: 10600, eng: 9.4, gender: 73, age: '24-36' },
  { name: 'Kit Albright', handle: '@kitalbright', categories: ['Lifestyle'], followers: 5200, eng: 12.8, gender: 81, age: '24-34' },
  { name: 'Lana Park', handle: '@lanaparked', categories: ['Beauty', 'Skincare'], followers: 17200, eng: 7.7, gender: 93, age: '24-34' },
  { name: 'Marin Cole', handle: '@marincole', categories: ['Home', 'Wellness'], followers: 6500, eng: 10.6, gender: 86, age: '28-40' },
  { name: 'Noa Schaefer', handle: '@noaschaefer', categories: ['Fashion', 'Lifestyle'], followers: 12700, eng: 8.9, gender: 79, age: '24-34' },
  { name: 'Posie Drake', handle: '@posiedrake', categories: ['Beauty', 'Fashion'], followers: 4300, eng: 14.5, gender: 90, age: '20-30' },
  { name: 'Reese Lambert', handle: '@reeselambert', categories: ['Wellness', 'Holistic'], followers: 8100, eng: 10.3, gender: 85, age: '26-38' },
  { name: 'Sutton Vale', handle: '@suttonvale', categories: ['Lifestyle', 'Home'], followers: 15600, eng: 7.8, gender: 80, age: '28-42' },
];

const colors = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W'];

function makeFirstName(name) { return name.split(' ')[0]; }

const minimalPrefs = (about) => ({
  ...emptyPrefs(),
  about: about ?? '',
});

const cities = [
  'Austin, TX', 'Seattle, WA', 'Denver, CO', 'Atlanta, GA', 'Chicago, IL',
  'San Diego, CA', 'Nashville, TN', 'Brooklyn, NY', 'Phoenix, AZ', 'Boston, MA',
];

export const GENERIC_CREATORS = GENERIC_POOL.slice(0, 43).map((p, i) => {
  const socials = i % 3 === 0 ? ['instagram'] : (i % 3 === 1 ? ['tiktok'] : ['instagram','tiktok']);
  return {
    id: `cr_g${String(i + 1).padStart(2, '0')}`,
    name: p.name,
    firstName: makeFirstName(p.name),
    handle: p.handle,
    benableHandle: p.handle.replace('@','').toLowerCase(),
    email: `${p.handle.replace('@','').toLowerCase()}@gmail.com`,
    phone: `+1 555 ${(200 + i * 7).toString().padStart(3,'0')} ${(1000 + i * 13).toString().slice(-4)}`,
    locationCity: cities[i % cities.length],
    contentNiche: p.categories.join(' + '),
    avatarColor: colors[i % colors.length],
    bioAiOptimized: false,
    socials,
    followerCount: p.followers,
    engagementRate: p.eng,
    platformStats: {
      instagram: { followers: socials.includes('instagram') ? p.followers : 0, engagement: socials.includes('instagram') ? p.eng : 0 },
      tiktok: { followers: socials.includes('tiktok') ? Math.round(p.followers * 0.7) : 0, engagement: socials.includes('tiktok') ? Math.max(8, p.eng - 1) : 0 },
    },
    contentFormatStrengths: i % 2 === 0 ? ['reels', 'carousels'] : ['stories', 'face-to-camera'],
    audience: { location: 'United States', genderFemalePct: p.gender, ageRange: p.age },
    audienceTopLocations: [{ name: 'United States', pct: 78 + (i % 12) }],
    categories: p.categories,
    preferences: minimalPrefs(`${p.categories.join(' / ')} creator.`),
    onboardingStatus: 'pending',
    logistics: defaultLogistics(),
    contentTypePreference: 'open-to-both',
  };
});

export const SEED_CREATORS = [...FEATURE_CREATORS, ...GENERIC_CREATORS];
