// Empty / partial preferences template
const emptyPrefs = () => ({
  workWith: '',
  avoid: '',
  giftedOpenness: '',
  smallBrands: null,        // 'yes' | 'maybe' | 'no' | null
  smallBrandsNote: '',
  unknownBrands: null,
  unknownBrandsNote: '',
  dreamHousehold: '',
  dreamNiche: '',
  dreamLocal: '',
  about: '',
});

const featurePrefs = {
  cr_dani: {
    about: "Skincare and beauty creator focused on clean ingredients and ethical brands.",
    workWith: "Science-backed, clean ingredients, honest ethics, woman-owned",
    avoid: "Creative freedom being taken away / content altered without credit",
    giftedOpenness: "Open — this is where I'm currently starting",
    smallBrands: 'maybe',
    smallBrandsNote: 'Cautious about ingredients/ethics',
    unknownBrands: 'maybe',
    unknownBrandsNote: 'Same — needs to trust the company',
    dreamHousehold: 'Naturium, Ninja, Costco, Shark',
    dreamNiche: 'Wildfleur, Sprouts',
    dreamLocal: '',
  },
  cr_sage: {
    about: "Mom-life creator — beauty, motherhood, wellness, lifestyle.",
    workWith: "Motherhood, lifestyle, beauty, wellness — clean, non-toxic, practical for mom life",
    avoid: "Not family-friendly, controversial, misleading, low-quality",
    giftedOpenness: "Very open, thankful to be gifted",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'Dyson, Dove, Honest Company',
    dreamNiche: 'Odele Beauty, Branch Basics',
    dreamLocal: 'Gabi Coffee, Mothership Coffee',
  },
  cr_haley: {
    about: "Family content creator covering kids, pets, home, garden.",
    workWith: "Beauty, clothing, pet, kids, outdoor/garden, home, services",
    avoid: "Alcohol (doesn't drink)",
    giftedOpenness: "Open to most!",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'ThredUp, Shark, Love Sac, Quince',
    dreamNiche: 'Crudités, Hulken, Petajane',
    dreamLocal: '',
  },
  cr_ellie: {
    about: "Activewear & beauty creator with a polished, fashion-forward aesthetic.",
    workWith: "Activewear, fashion, skincare, beauty",
    avoid: "Vitamins, food, technology, undergarments, dietary items",
    giftedOpenness: "Very open",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'Vuori, Rhode, H&M, Bloom Nutrition',
    dreamNiche: 'Set Active, Peppermayo, Saie Beauty',
    dreamLocal: 'Sorbo, Timpano, The Salty Donut',
  },
  cr_rylan: {
    about: "Lifestyle creator open to almost any partnership.",
    workWith: "Anyone",
    avoid: "Underwear or sex",
    giftedOpenness: "Very open",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: '',
    dreamNiche: '',
    dreamLocal: '',
  },
  cr_willow: {
    about: "Holistic wellness, clean home, natural living creator.",
    workWith: "Clean ingredients, holistic, natural living, home decor, wellness",
    avoid: "Unsustainable wellness practices",
    giftedOpenness: "Open",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'Purely Elizabeth, Innersense Organic Beauty, Lesser Evil',
    dreamNiche: 'Synergy, Siggs, Bizzy, HU',
    dreamLocal: 'Nitro Bar (RI)',
  },
  cr_carla: {
    about: "Beauty creator focused on clean-ingredient routines.",
    workWith: "Clean ingredients",
    avoid: "",
    giftedOpenness: "Very open",
    smallBrands: 'yes',
    smallBrandsNote: '',
    unknownBrands: 'yes',
    unknownBrandsNote: '',
    dreamHousehold: 'Rhode, Youth to the People',
    dreamNiche: 'Culture Pop, Vista Hermosa',
    dreamLocal: 'Sweetgreen, Butterfish',
  },
};

// 7 named feature creators with full data
export const FEATURE_CREATORS = [
  {
    id: 'cr_dani',
    name: 'Dani Brooks',
    firstName: 'Dani',
    handle: '@glowingwithdani',
    email: 'dani@glowingwithdani.com',
    phone: '+1 555 234 1101',
    avatarColor: 'A',
    socials: ['instagram', 'tiktok'],
    followerCount: 4200,
    engagementRate: 18.4,
    audience: { location: 'United States', genderFemalePct: 91, ageRange: '24-34' },
    categories: ['Beauty', 'Skincare', 'Clean Living'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_dani },
    onboardingStatus: 'complete',
  },
  {
    id: 'cr_sage',
    name: 'Sage Apostadiro',
    firstName: 'Sage',
    handle: '@sageylovee',
    email: 'sage@sageylovee.com',
    phone: '+1 555 234 1102',
    avatarColor: 'B',
    socials: ['instagram'],
    followerCount: 12800,
    engagementRate: 9.2,
    audience: { location: 'United States', genderFemalePct: 88, ageRange: '28-38' },
    categories: ['Motherhood', 'Lifestyle', 'Wellness'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_sage },
    onboardingStatus: 'complete',
  },
  {
    id: 'cr_haley',
    name: 'Haley Brennan',
    firstName: 'Haley',
    handle: '@haleysathome',
    email: 'haley@haleysathome.com',
    phone: '+1 555 234 1103',
    avatarColor: 'C',
    socials: ['instagram', 'tiktok'],
    followerCount: 8400,
    engagementRate: 7.1,
    audience: { location: 'United States', genderFemalePct: 84, ageRange: '30-44' },
    categories: ['Home', 'Family', 'Outdoor'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_haley },
    onboardingStatus: 'partial', // matches "Invited stalled" demo state
  },
  {
    id: 'cr_ellie',
    name: 'Ellie Stuart',
    firstName: 'Ellie',
    handle: '@elliestu20',
    email: 'ellie@elliestuart.com',
    phone: '+1 555 234 1104',
    avatarColor: 'D',
    socials: ['instagram'],
    followerCount: 6900,
    engagementRate: 11.8,
    audience: { location: 'United States', genderFemalePct: 79, ageRange: '20-30' },
    categories: ['Fashion', 'Activewear', 'Beauty'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_ellie },
    onboardingStatus: 'complete',
  },
  {
    id: 'cr_rylan',
    name: 'Rylan Matu',
    firstName: 'Rylan',
    handle: '@rylanmatu',
    email: 'rylan@rylanmatu.com',
    phone: '+1 555 234 1105',
    avatarColor: 'E',
    socials: ['tiktok'],
    followerCount: 21600,
    engagementRate: 14.5,
    audience: { location: 'United States', genderFemalePct: 72, ageRange: '18-28' },
    categories: ['Lifestyle', 'Beauty'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_rylan },
    onboardingStatus: 'complete',
  },
  {
    id: 'cr_willow',
    name: 'Willow Key',
    firstName: 'Willow',
    handle: '@willowkey33',
    email: 'willow@willowkey.com',
    phone: '+1 555 234 1106',
    avatarColor: 'F',
    socials: ['instagram', 'tiktok'],
    followerCount: 9500,
    engagementRate: 13.0,
    audience: { location: 'United States', genderFemalePct: 86, ageRange: '26-38' },
    categories: ['Wellness', 'Home', 'Holistic'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_willow },
    onboardingStatus: 'complete',
  },
  {
    id: 'cr_carla',
    name: 'Carla Guillarte',
    firstName: 'Carla',
    handle: '@carlacharisse',
    email: 'carla@carlacharisse.com',
    phone: '+1 555 234 1107',
    avatarColor: 'G',
    socials: ['instagram'],
    followerCount: 5100,
    engagementRate: 16.2,
    audience: { location: 'United States', genderFemalePct: 89, ageRange: '24-34' },
    categories: ['Beauty', 'Skincare'],
    preferences: { ...emptyPrefs(), ...featurePrefs.cr_carla },
    onboardingStatus: 'complete',
  },
];

// Pool of plausible creator data for the 43 generic creators
const GENERIC_POOL = [
  { name: 'Avery Lin', handle: '@averythelin', categories: ['Lifestyle', 'Fashion'], followers: 3400, eng: 9.1, gender: 78, age: '22-32' },
  { name: 'Bri Sanders', handle: '@brisanders', categories: ['Beauty', 'Skincare'], followers: 7200, eng: 11.5, gender: 92, age: '24-34' },
  { name: 'Camila Rios', handle: '@camilariosss', categories: ['Fashion', 'Travel'], followers: 11400, eng: 8.4, gender: 81, age: '25-35' },
  { name: 'Drea Park', handle: '@dreaparkliving', categories: ['Home', 'Lifestyle'], followers: 5600, eng: 12.3, gender: 87, age: '28-40' },
  { name: 'Esme Tucker', handle: '@esmetucks', categories: ['Wellness', 'Fitness'], followers: 9100, eng: 10.7, gender: 74, age: '23-33' },
  { name: 'Faye Romero', handle: '@fayeromero', categories: ['Motherhood', 'Family'], followers: 18500, eng: 6.9, gender: 95, age: '30-44' },
  { name: 'Gianna Webb', handle: '@giannaweb', categories: ['Beauty'], followers: 4200, eng: 14.2, gender: 90, age: '20-30' },
  { name: 'Hadley Kim', handle: '@hadleyk', categories: ['Lifestyle', 'Beauty'], followers: 22300, eng: 7.5, gender: 82, age: '26-36' },
  { name: 'Imani Joseph', handle: '@imanijoseph', categories: ['Fashion', 'Beauty'], followers: 6700, eng: 11.1, gender: 88, age: '24-34' },
  { name: 'Jules Bishop', handle: '@julesatcasa', categories: ['Home', 'Decor'], followers: 14200, eng: 9.8, gender: 79, age: '30-44' },
  { name: 'Kira Pham', handle: '@kirapham', categories: ['Wellness', 'Beauty'], followers: 8900, eng: 12.6, gender: 86, age: '26-38' },
  { name: 'Lila Anders', handle: '@lilaanders', categories: ['Lifestyle', 'Travel'], followers: 5300, eng: 13.8, gender: 76, age: '22-32' },
  { name: 'Mira Owens', handle: '@miraowens', categories: ['Fitness', 'Wellness'], followers: 16800, eng: 8.2, gender: 71, age: '24-34' },
  { name: 'Nia Carter', handle: '@niacarterlife', categories: ['Beauty', 'Skincare'], followers: 4800, eng: 15.4, gender: 93, age: '22-32' },
  { name: 'Opal Reyes', handle: '@opalreyes', categories: ['Fashion'], followers: 10300, eng: 9.5, gender: 84, age: '25-35' },
  { name: 'Piper Wynn', handle: '@piperwynn', categories: ['Motherhood', 'Beauty'], followers: 7600, eng: 10.9, gender: 94, age: '28-40' },
  { name: 'Quinn Holloway', handle: '@quinnholloway', categories: ['Lifestyle', 'Home'], followers: 12100, eng: 8.7, gender: 80, age: '28-42' },
  { name: 'Rae Castillo', handle: '@raecastillo', categories: ['Beauty', 'Fashion'], followers: 4500, eng: 13.1, gender: 89, age: '20-30' },
  { name: 'Sloane Patel', handle: '@sloanepatel', categories: ['Wellness', 'Holistic'], followers: 9700, eng: 11.4, gender: 85, age: '26-38' },
  { name: 'Tess Greaves', handle: '@tessgreaves', categories: ['Lifestyle', 'Family'], followers: 6300, eng: 10.2, gender: 88, age: '30-44' },
  { name: 'Uma Brooks', handle: '@umab', categories: ['Beauty'], followers: 3100, eng: 16.0, gender: 91, age: '20-30' },
  { name: 'Vera Goodall', handle: '@verakindly', categories: ['Wellness', 'Fitness'], followers: 13500, eng: 7.9, gender: 76, age: '24-36' },
  { name: 'Wren Davies', handle: '@wrendavies', categories: ['Fashion', 'Travel'], followers: 8200, eng: 9.3, gender: 81, age: '26-36' },
  { name: 'Xio Mendez', handle: '@xiomendez', categories: ['Beauty', 'Lifestyle'], followers: 5900, eng: 12.0, gender: 87, age: '22-32' },
  { name: 'Yasmin Day', handle: '@yasminday', categories: ['Motherhood', 'Wellness'], followers: 19400, eng: 6.4, gender: 96, age: '32-44' },
  { name: 'Zoe Anand', handle: '@zoeaanand', categories: ['Lifestyle'], followers: 4000, eng: 14.7, gender: 83, age: '22-32' },
  { name: 'Adair Hunt', handle: '@adairhunt', categories: ['Home', 'Lifestyle'], followers: 7400, eng: 10.5, gender: 78, age: '28-42' },
  { name: 'Bex McCoy', handle: '@bexmccoy', categories: ['Beauty', 'Skincare'], followers: 11900, eng: 8.6, gender: 92, age: '24-34' },
  { name: 'Cleo Tanaka', handle: '@cleotanaka', categories: ['Fashion'], followers: 25700, eng: 7.2, gender: 80, age: '22-32' },
  { name: 'Della Rivers', handle: '@dellarivers', categories: ['Beauty', 'Lifestyle'], followers: 6100, eng: 11.7, gender: 89, age: '24-34' },
  { name: 'Elsie Tate', handle: '@elsietate', categories: ['Wellness'], followers: 4700, eng: 13.3, gender: 84, age: '26-38' },
  { name: 'Frankie Locke', handle: '@frankielocke', categories: ['Lifestyle', 'Travel'], followers: 14800, eng: 8.0, gender: 75, age: '24-34' },
  { name: 'Greta Hollis', handle: '@gretahollis', categories: ['Home', 'Family'], followers: 9300, eng: 9.7, gender: 91, age: '30-44' },
  { name: 'Hattie Boyle', handle: '@hattieboyle', categories: ['Beauty'], followers: 3600, eng: 15.9, gender: 88, age: '20-30' },
  { name: 'Indi Stark', handle: '@indistark', categories: ['Fashion', 'Beauty'], followers: 8800, eng: 11.0, gender: 82, age: '22-32' },
  { name: 'Jovi Marsh', handle: '@jovimarsh', categories: ['Wellness', 'Fitness'], followers: 10600, eng: 9.4, gender: 73, age: '24-36' },
  { name: 'Kit Albright', handle: '@kitalbright', categories: ['Lifestyle'], followers: 5200, eng: 12.8, gender: 81, age: '24-34' },
  { name: 'Lana Park', handle: '@lanaparked', categories: ['Beauty', 'Skincare'], followers: 17200, eng: 7.7, gender: 93, age: '24-34' },
  { name: 'Marin Cole', handle: '@marincole', categories: ['Home', 'Wellness'], followers: 6500, eng: 10.6, gender: 86, age: '28-40' },
  { name: 'Noa Schaefer', handle: '@noaschaefer', categories: ['Fashion', 'Lifestyle'], followers: 12700, eng: 8.9, gender: 79, age: '24-34' },
  { name: 'Posie Drake', handle: '@posiedrake', categories: ['Beauty', 'Fashion'], followers: 4300, eng: 14.5, gender: 90, age: '20-30' },
  { name: 'Reese Lambert', handle: '@reeselambert', categories: ['Wellness', 'Holistic'], followers: 8100, eng: 10.3, gender: 85, age: '26-38' },
  { name: 'Sutton Vale', handle: '@suttonvale', categories: ['Lifestyle', 'Home'], followers: 15600, eng: 7.8, gender: 80, age: '28-42' },
];

const colors = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W'];

function makeFirstName(name) { return name.split(' ')[0]; }

const minimalPrefs = (about) => ({
  ...emptyPrefs(),
  about: about ?? '',
});

export const GENERIC_CREATORS = GENERIC_POOL.slice(0, 43).map((p, i) => ({
  id: `cr_g${String(i + 1).padStart(2, '0')}`,
  name: p.name,
  firstName: makeFirstName(p.name),
  handle: p.handle,
  email: `${p.handle.replace('@','').toLowerCase()}@gmail.com`,
  phone: `+1 555 ${(200 + i * 7).toString().padStart(3,'0')} ${(1000 + i * 13).toString().slice(-4)}`,
  avatarColor: colors[i % colors.length],
  socials: i % 3 === 0 ? ['instagram'] : (i % 3 === 1 ? ['tiktok'] : ['instagram','tiktok']),
  followerCount: p.followers,
  engagementRate: p.eng,
  audience: { location: 'United States', genderFemalePct: p.gender, ageRange: p.age },
  categories: p.categories,
  preferences: minimalPrefs(`${p.categories.join(' / ')} creator.`),
  onboardingStatus: 'pending', // overridden by event timeline below
}));

export const SEED_CREATORS = [...FEATURE_CREATORS, ...GENERIC_CREATORS];
